### ISSUE TITLE
Fazer Cadastro - US01

### ISSUE THREAD

**Issue by GabrielTiveron** [fga-eps-mds/2021-1-PUMA#10]
## Descrição:
Deve ser criada uma página de cadastro de usuário

## Tarefas
- [x] Fazer página de cadastro
- [x] Criar a rota de cadastro no backend
- [x] Conexão do frontend com o backend
- [ ] Armazenar informações de usuário na base de dados
- [x] Retornar resultado do cadastro

## Critério de aceitação:
- [x] O usuário deve conseguir seguir o fluxo de cadastro
- [x] O usuário deve estar cadastrado na base de dados
- [ ] Funcionalidade deve estar testada
