### ISSUE TITLE
Fazer Login - US02

### ISSUE THREAD

**Issue by GabrielTiveron** [fga-eps-mds/2021-1-PUMA#11]
## Descrição:
Possibilitar o login de usuários

## Tarefas
- [ ] Fazer página de login
- [ ] Criar a rota de login no backend
- [ ] Conexão do frontend com o backend
- [ ] Autenticar informações do usuário
- [ ] Retornar resultado do login
- [ ] Redirecionar à página inicial

## Critério de aceitação:
- [ ]  O usuário deve conseguir seguir o fluxo de login
- [ ]  O usuário deve ser autenticado no backend
- [ ]  O usuário deve possuir uma sessão de acesso
- [ ]  Funcionalidade deve estar testada
